site_name: AFOIer
site_url: https://afoier.wiki
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - 首页: index.md
  - 高校信息:
    - 强基计划:
      - 总述: colleges/oh.md
      - 泛信息类专业汇总: colleges/oh-cs.md
    - 综合评价招生:
      - 总述: colleges/admission-outline.md
    - 省份单独招生机制:
      - 总述: colleges/admission-provinces.md
    - 保研与考研: colleges/postgraduate.md
    - 出国留学: colleges/overseas.md
  - 关于: about.md
  - 沙盒:
    - 二级目录:
      - 测试页面1: sandbox/page1.md
      - 三级目录:
        - 测试页面2: sandbox/page2.md