site_name: AFOIer
site_url: https://afoier.wiki
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - 首页: index.md
  - 高校信息:
    - 强基计划:
      - 总述: colleges/oh.md
      - 泛信息类专业汇总: colleges/oh-cs.md
    - 综合评价招生:
      - 总述: colleges/admission-outline.md
    - 省份单独招生机制:
      - 总述: colleges/admission-provinces.md
    - 保研与考研: colleges/postgraduate.md
    - 出国留学: colleges/overseas.md
    - 港新申请: colleges/afoier-db.md
  - 文化课:
    - 通用建议: whk/general.md
    - 贡献指南: whk/contribution.md
    - 工具资料:
      - 总述: whk/resources/index.md
    - 语文:
      - 总述: whk/subjects/chinese/index.md
    - 数学:
      - 总述: whk/subjects/maths/index.md
    - 英语:
      - 总述: whk/subjects/english/index.md
    - 外语小语种（非英语）:
      - 总述: whk/subjects/foreign-language/index.md
    - 物理:
      - 总述: whk/subjects/physics/index.md
    - 化学:
      - 总述: whk/subjects/chemistry/index.md
    - 生物:
      - 总述: whk/subjects/biology/index.md
    - 地理:
      - 总述: whk/subjects/geography/index.md
    - 思想政治:
      - 总述: whk/subjects/politics/index.md
    - 历史:
      - 总述: whk/subjects/history/index.md
    - 技术（浙江）:
      - 总述: whk/subjects/technology/index.md
  - 社区:
    - 退役心路: stories/index.md
    - 就读体验: experience/index.md
    - 职业发展:
      - 总览: careers/roadmap.md
      - 投稿: careers/index.md
  - 资源:
    - 竞赛词典: glossary.md
    - 学习资源: resources/index.md
  - 关于: about.md
  - 沙盒:
    - 二级目录:
      - 测试页面1: sandbox/page1.md
      - 三级目录:
        - 测试页面2: sandbox/page2.md
